# Generated by Django 5.2.5 on 2025-10-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='streak',
        ),
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], default='Not Done', max_length=20),
        ),
    ]
