# Generated by Django 5.2.5 on 2025-10-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_type',
            new_name='todays_workout',
        ),
    ]
